parameters:
  - name: env
    type: string
    
  - name: wallet
    type: string

  - name: wallets
    type: object
    default:
      - true
      - false

  - name: arezzo
    type: boolean
    default: false

  - name: alme
    type: boolean
    default: false

  - name: fiever
    type: boolean
    default: false

  - name: birman
    type: boolean
    default: false

  - name: schutz
    type: boolean
    default: false

  - name: anacapri
    type: boolean
    default: false

  - name: vans
    type: boolean
    default: false

  - name: zzmall
    type: boolean
    default: false

stages:
  - stage: "MavenTestEcommerceStage"
    displayName: "${{ parameters.env }} - Maven Test Ecommerce Stage"

    jobs:
      - job: "MavenTestEcommerceJob_"
        displayName: "Maven Test Ecommerce Job"

        timeoutInMinutes: 0

        strategy:
          matrix:
            ${{ each value in parameters.wallets }}:
              ${{ if in(parameters.wallet, value, 'all') }}:
                ${{ if eq(parameters.arezzo, true) }}:
                  Arezzo${{value}}:
                    flavor: 'Arezzo'


                ${{ if eq(parameters.alme, true) }}:
                  Alme${{value}}:
                    flavor: 'Owme'

                ${{ if eq(parameters.fiever, true) }}:
                  Fiever${{value}}:
                    flavor: 'Fiever'

                ${{ if eq(parameters.birman, true) }}:
                  Birman${{value}}:
                    flavor: 'AlexandreBirman'

                ${{ if eq(parameters.schutz, true) }}:
                  Schutz${{value}}:
                    flavor: 'Schutz'

                ${{ if eq(parameters.anacapri, true) }}:
                  Anacapri${{value}}:
                    flavor: 'Anacapri'

                ${{ if eq(parameters.vans, true) }}:
                  Vans${{value}}:
                    flavor: 'Vans'

                ${{ if eq(parameters.zzmall, true) }}:
                  ZZMall${{value}}:
                    flavor: 'Zzmall'

        variables:
          - group: automationAPI

        steps:
          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsArezzo)"
            displayName: 'Set additionalTags Arezzo'
            condition: and(succeeded(), eq(variables.flavor, 'Arezzo'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsAlme)"
            displayName: 'Set additionalTags Alme'
            condition: and(succeeded(), eq(variables.flavor, 'Owme'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsFiever)"
            displayName: 'Set additionalTags Fiever'
            condition: and(succeeded(), eq(variables.flavor, 'Fiever'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsBirman)"
            displayName: 'Set additionalTags Birman'
            condition: and(succeeded(), eq(variables.flavor, 'AlexandreBirman'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsSchutz)"
            displayName: 'Set additionalTags Schutz'
            condition: and(succeeded(), eq(variables.flavor, 'Schutz'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsAnacapri)"
            displayName: 'Set additionalTags Anacapri'
            condition: and(succeeded(), eq(variables.flavor, 'Anacapri'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsVans)"
            displayName: 'Set additionalTags Vans'
            condition: and(succeeded(), eq(variables.flavor, 'Vans'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsZzmall)"
            displayName: 'Set additionalTags Zzmall'
            condition: and(succeeded(), eq(variables.flavor, 'Zzmall'))

          - script: |
              echo "Flavor: $(flavor)"
              echo "Mode: $(currMode)"
              echo "AdditionalTags: $(additionalTags)"
            displayName: 'Debugging Job parameters'
            env:
              MY_VARIABLES: $(additionalTags)

          - task: Maven@3
            displayName: 'Runnin maven test'
            continueOnError: true
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.8"
              jdkArchitectureOption: 'x64'
              goals: "clean test"
              options: >-
                -Djvm.options=-Xss50000k
                -Dbrand=$(flavor)
                -Denv=${{ parameters.env }}
                -Dwallet=$(currMode)