parameters:
  - name: env
    type: string

  - name: wallet
    type: boolean

  - name: task
    type: string

  - name: arezzo
    type: boolean
    default: false

  - name: alme
    type: boolean
    default: false

  - name: fiever
    type: boolean
    default: false

  - name: birman
    type: boolean
    default: false

  - name: schutz
    type: boolean
    default: false

  - name: anacapri
    type: boolean
    default: false

  - name: vans
    type: boolean
    default: false

  - name: zzmall
    type: boolean
    default: false

stages:
  - stage: "MavenTestEcommerceStage"
    displayName: "${{ parameters.env }} - Maven Test Ecommerce Stage"

    jobs:
      - job: "MavenTestEcommerceJob"
        displayName: "Maven Test Ecommerce Job"

        timeoutInMinutes: 0

        strategy:
          matrix:
            ${{ each value in parameters.modes }}:
              ${{ if in(parameters.mode, value, 'all') }}:
                ${{ if eq(parameters.arezzo, true) }}:
                  Arezzo${{value}}:
                    flavor: 'Arezzo'
                    currMode: ${{value}}

                ${{ if eq(parameters.alme, true) }}:
                  Alme${{value}}:
                    flavor: 'Owme'
                    currMode: ${{value}}

                ${{ if eq(parameters.fiever, true) }}:
                  Fiever${{value}}:
                    flavor: 'Fiever'
                    currMode: ${{value}}

                ${{ if eq(parameters.birman, true) }}:
                  Birman${{value}}:
                    flavor: 'AlexandreBirman'
                    currMode: ${{value}}

                ${{ if eq(parameters.schutz, true) }}:
                  Schutz${{value}}:
                    flavor: 'Schutz'
                    currMode: ${{value}}

                ${{ if eq(parameters.anacapri, true) }}:
                  Anacapri${{value}}:
                    flavor: 'Anacapri'
                    currMode: ${{value}}

                ${{ if eq(parameters.vans, true) }}:
                  Vans${{value}}:
                    flavor: 'Vans'
                    currMode: ${{value}}

                ${{ if eq(parameters.zzmall, true) }}:
                  ZZMall${{value}}:
                    flavor: 'Zzmall'
                    currMode: ${{value}}

        variables:
          - group: automationAPI

        steps:
          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsArezzoDesktop)"
            displayName: 'Set additionalTags Arezzo Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'Arezzo'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsArezzoMobile)"
            displayName: 'Set additionalTags Arezzo Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'Arezzo'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsAlmeDesktop)"
            displayName: 'Set additionalTags Alme Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'Owme'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsAlmeMobile)"
            displayName: 'Set additionalTags Alme Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'Owme'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsFieverDesktop)"
            displayName: 'Set additionalTags Fiever Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'Fiever'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsFieverMobile)"
            displayName: 'Set additionalTags Fiever Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'Fiever'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsBirmanDesktop)"
            displayName: 'Set additionalTags Birman Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'AlexandreBirman'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsBirmanMobile)"
            displayName: 'Set additionalTags Birman Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'AlexandreBirman'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsSchutzDesktop)"
            displayName: 'Set additionalTags Schutz Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'Schutz'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsSchutzMobile)"
            displayName: 'Set additionalTags Schutz Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'Schutz'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsAnacapriDesktop)"
            displayName: 'Set additionalTags Anacapri Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'Anacapri'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsAnacapriMobile)"
            displayName: 'Set additionalTags Anacapri Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'Anacapri'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsVansDesktop)"
            displayName: 'Set additionalTags Vans Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'Vans'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsVansMobile)"
            displayName: 'Set additionalTags Vans Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'Vans'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsZzmallDesktop)"
            displayName: 'Set additionalTags Zzmall Desktop'
            condition: and(succeeded(), eq(variables.flavor, 'Zzmall'), eq(variables.currMode, 'Desktop'))

          - script: |
              echo "##vso[task.setvariable variable=additionalTags]$(tagsZzmallMobile)"
            displayName: 'Set additionalTags Zzmall Mobile'
            condition: and(succeeded(), eq(variables.flavor, 'Zzmall'), eq(variables.currMode, 'Mobile'))

          - script: |
              echo "Flavor: $(flavor)"
              echo "AdditionalTags: $(additionalTags)"
              echo "Wallet: ${{ parameters.wallet }}"
            displayName: 'Debugging Job parameters'
            env:
              MY_VARIABLES: $(additionalTags)

          - task: Maven@3
            displayName: 'Runnin maven test'
            continueOnError: true
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.8"
              jdkArchitectureOption: 'x64'
              goals: "clean test"
              options: >-
                -Djvm.options=-Xss50000k
                -Dbrand=$(flavor)
                -Denv=${{ parameters.env }}
                -DexcludeWallet=${{ parameters.wallet }}